services:
  # Service Backend API
  - type: web
    name: skillfusion-perso-backend
    env: node
    plan: free
    buildCommand: npm install && npm run db:create && npm run db:seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 24h
      - key: PG_URL
        fromDatabase:
          name: skillfusion-db-1
          property: connectionString
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com

  # Base de donn√©es PostgreSQL
  - type: pserv
    name: skillfusion-db-1
    env: postgresql
    plan: free
    ipAllowList: []
